### ISSUE TITLE
Cannot found pre-train model

### ISSUE THREAD

**Issue by hungnvk54** [julik43/Online-Identification-of-New-Speakers#1]
Hi developer,
Can you provides the pre-train model for Voxceleb 2 corpus. 
Thanks you in advances

**Comment by julik43** [comment]
We are working on loading this weights in our server. We hope to have the updated link in the next hours.

**Comment by julik43** [comment]
The link is updated.

**Comment by hungnvk54** [comment]
> The link is updated.

Thanks you so much
