### ISSUE TITLE
A little doubt about the structure of the R50 model

### ISSUE THREAD

**Issue by lyu-joe** [julik43/Online-Identification-of-New-Speakers#2]
hi,i have read the paper this project cited ,i have a little doubt about the structure of the R50 model,
there is only one average pooling layer and one max pooling layer in the R50 model structure file,
why you set pool_layers 3 in the config_R50_Spec32.json file

**Comment by julik43** [comment]
Because at the beginning there is a convolution with a stride of 2, which also downsize the input in half, so I add (my bad) that reduction as a pooling layer in the parameter, maybe a better name for that would have been downsize_rate instead of pool_layers, to contemplate all kind of reductions.

**Comment by lyu-joe** [comment]
> Because at the beginning there is a convolution with a stride of 2, which also downsize the input in half, so I add (my bad) that reduction as a pooling layer in the parameter, maybe a better name for that would have been downsize_rate instead of pool_layers, to contemplate all kind of reductions.
thank you for your quick reply,can you provide the download link of pre-trained R50 model for Voxceleb 2 corpus. And by the way  ,Is rounds_train*num_train_files*n_row_tf_record a constant . or  I can change it by myself  thanks again.

**Comment by lyu-joe** [comment]
> Because at the beginning there is a convolution with a stride of 2, which also downsize the input in half, so I add (my bad) that reduction as a pooling layer in the parameter, maybe a better name for that would have been downsize_rate instead of pool_layers, to contemplate all kind of reductions.

thank you for your quick reply,can you provide the download link of pre-trained R50 model for Voxceleb 2 corpus. And by the way ,Is rounds_train * num_train_files * n_row_tf_record a constant . or I can change it by myself thanks again

**Comment by lyu-joe** [comment]
> Because at the beginning there is a convolution with a stride of 2, which also downsize the input in half, so I add (my bad) that reduction as a pooling layer in the parameter, maybe a better name for that would have been downsize_rate instead of pool_layers, to contemplate all kind of reductions.

thank you for your quick reply,can you provide the download link of pre-trained R50 model for Voxceleb 2 corpus. And by the way ,Is rounds_train * num_train_files * n_row_tf_record a constant . or in other words , does it matter  if the training process I designed does not have rounds,i set new num_train_files = rounds_train * num_train_files  and delete the rounds parameter
